### ISSUE TITLE
Embed Icons?

### ISSUE THREAD

**Issue by zorro-weaver** [oatear/cider#36]
Most card game prototyping software has the ability replace certain strings with images in the descriptions of cards. As of now, it doesn't appear that it's possible within the current system, but it'd certainly be a welcome if not essential feature. If there is a way to do so currently, please inform me! Thanks.

**Comment by hristoiankov** [comment]
Yes, there is a way to do this.

In your template you have to setup a `{{compileImages` helper

Ex.
`<div>{{compileImages card.description width=100}}<div>`

In your cards table for the description field in this example any {{image-name}} will be converted into images from your assets listing. The bellow example assumes you have a red-card image in your assets page.

Ex. description field value
`Draw {{red-card 2}}, discard {{red-card}}.`

Ref: https://github.com/oatear/cider/blob/main/HANDLEBARS.md#compile-images-compileimages

**Comment by zorro-weaver** [comment]
Thanks a lot, that's exactly what I was looking for. I did run into one issue though. 

Though they should all be the same height, some of my icons are wider than the others. Instead of setting a width for all of the images, it'd be nicer to be able to set a common height and automatically set the width. Using "height" doesn't seem to work. Is there an alternative method of doing this?

**Comment by hristoiankov** [comment]
Yes, the width attribute is optional. You can size the images as you want before you upload them. `{{compileImages card.description}}`. You can also style them through the template's .css. Since `{{compileImages}}` really just injects `<img>` tags, you can set styling to size those images as you would like. Otherwise, I can add in an optional height parameter that will function as you were describing.
